Numerical Python - Numpy


Advantages of Arrays in Numpy:


*   Allows several Mathematical Operations
*   Faster Operation




In [ ]:
import numpy as np

List vs Numpy - Time Taken

In [ ]:
from time import process_time

Time taken by a list

In [ ]:
python_list = [i for i in range (10000)]

start_time = process_time()

python_list = [i+5 for i in python_list]

end_time = process_time()

print(end_time - start_time)

0.001363705999999354


In [ ]:
np_array = np.array([i for i in range(1000)])

start_time = process_time()

np_array += 5 # np_array = np_array + 5

end_time = process_time()

print(end_time - start_time)

0.0016002499999991926


Numpy Arrays

In [ ]:
# list

list1 = [1,2,3,4,5]
print(list1)
type(list1)
print(list1)
type(list1)

[1, 2, 3, 4, 5]
[1, 2, 3, 4, 5]


list

In [ ]:
import numpy as np

np_array = np.array([1,2,3,4,5])
print(np_array)
type(np_array)

[1 2 3 4 5]


numpy.ndarray

In [ ]:
# Creatig 1 D array
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [ ]:
a.shape

(4,)

In [ ]:
b = np.array([(1,2,3,4),(5,6,7,8)])
print(b)

[[1 2 3 4]
 [5 6 7 8]]


In [ ]:
b.shape

(2, 4)

In [ ]:
c = np.array([(1,2,3,4),(5,6,7,8)],dtype=float)
print(c)

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]


Initial Placeholder in numpy arrays

In [ ]:
# Create a bunpy array of Zero
x = np.zeros((4,5))
print(x)

: 

In [ ]:
# Create a numpy array of ones
y = np.ones((3,3))
print(y)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
# Array of a particular value
z = np.full((5,4),5)
print(z)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [ ]:
# Create an identity matrix
a = np.eye(5)
print(a)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [ ]:
# Create a numpy array with random values
b = np.random.random((3,4))
print(b)

[[0.33200822 0.13784699 0.86542447 0.05678324]
 [0.90393125 0.60474348 0.76546498 0.02770164]
 [0.52088197 0.03970197 0.00193991 0.62306126]]


In [ ]:
# Random integer values array within a specific range
c = np.random.randint(10,100,(3,5))
print(c)

[[97 37 54 61 36]
 [14 54 91 11 87]
 [14 45 68 26 36]]


In [ ]:
# Array of evemly spaced values: Specifying the number of values required
d = np.linspace(10,30,6)
print(d)

[10. 14. 18. 22. 26. 30.]


In [ ]:
# Array of evenly spaced values: specifying the step
e = np.arange(10,30,5)
print(e)

[10 15 20 25]


In [ ]:
# Convert a list into a numpy array
list2 = [10,20,20,20,50]

np_array = np.asarray(list2)
print(np_array)
type(np_array)

[10 20 20 20 50]


numpy.ndarray

Analysing a numpy array

In [ ]:
c = np.random.randint(10,90,(5,5))
print(c)

[[80 24 49 26 25]
 [31 41 61 76 30]
 [58 26 16 82 56]
 [32 67 27 45 42]
 [53 38 24 25 80]]


In [ ]:
# Array dimension
print(c.shape)

(5, 5)


In [ ]:
# Number of dimension
print(c.ndim)

2


In [ ]:
# Number of elements in an array
print(c.size)

25


In [ ]:
# Checking the data type of the value in an array
print(c.dtype)

int64


Mathematical Operations on a numpy array

In [ ]:
list1 = [1,2,3,4,5]
list2 = [6,7,8,9,10]

print(list1 + list2) # Concatenate or joins two list

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [ ]:
import numpy as np

a = np.random.randint(0,10,(3,3))
b = np.random.randint(10,20,(3,3))


In [ ]:
print(a)
print(b)

[[3 9 2]
 [2 1 5]
 [9 8 0]]
<module 'numpy.random' from '/usr/local/lib/python3.10/dist-packages/numpy/random/__init__.py'>


In [ ]:
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[[16 24 21]
 [20 25 19]
 [24 11 19]]
[[ -8  -8 -13]
 [-10 -13 -15]
 [-10  -9 -17]]
[[ 48 128  68]
 [ 75 114  34]
 [119  10  18]]
[[0.33333333 0.5        0.23529412]
 [0.33333333 0.31578947 0.11764706]
 [0.41176471 0.1        0.05555556]]


In [ ]:
a = np.random.randint(0,10,(3,3))
b = np.random.randint(10,20,(3,3))

In [11]:
print(a)
print(b)

[[5 4 6]
 [7 2 9]]
[[5 4]
 [6 7]
 [2 9]]


In [17]:
b_transposed = b.T
print(np.add(a, b_transposed))
print(np.subtract(a, b_transposed))
print(np.multiply(a, b_transposed))
print(np.divide(a, b_transposed))


[[10 10  8]
 [11  9 18]]
[[ 0 -2  4]
 [ 3 -5  0]]
[[25 24 12]
 [28 14 81]]
[[1.         0.66666667 3.        ]
 [1.75       0.28571429 1.        ]]


Array manipulation

In [14]:
array = np.random.randint(0,10,(2,3))
print(array)
print(array.shape)

[[2 0 6]
 [8 8 6]]
(2, 3)


In [ ]:
# Transpose
trans = np.transpose(array)
print(trans)
print(trans.shape)

In [7]:
# Reshaping a array
import numpy as np
a = np.random.randint(0,10,(2,3))
print(a)
print(a.shape)

[[5 4 6]
 [7 2 9]]
(2, 3)


In [8]:
import numpy as np

b = a.reshape(3,2)
print(b)
print(b.shape)

[[5 4]
 [6 7]
 [2 9]]
(3, 2)
